### ISSUE TITLE
Need to update dependencies due to security issues

### ISSUE THREAD

**Issue by dkarchmer** [iotile/ng-iotile-cloud#143]
https://github.com/iotile/ng-iotile-cloud/network/alerts

**Comment by dkarchmer** [comment]
@matthieucharreire not sure how hard this will be but we should try to update. Talk to me if it won't be easy

**Comment by matthieucharreire** [comment]
I had a quick look at the issue, using `npm audit` & `npm audit fix`.

It seems that the package raising a critical alert is [`js-yaml`](https://www.npmjs.com/package/js-yaml) v0.3.x which is a dependency of `[jxLoader](https://www.npmjs.com/package/jxLoader?activeTab=versions)`(in v0.1.1 since 8 years), which itself is a dependency of `build` (in v0.1.4 since 7 years).

The critical issue with `js-yaml` [has been fixed 6 years ago.](https://www.npmjs.com/advisories/16/versions) So I guess I have to find a way to replace this `build` package.

**Comment by matthieucharreire** [comment]
@dkarchmer by the way I can not access [your link](https://github.com/iotile/ng-iotile-cloud/network/alerts), I get a 404.
So I don't really know what github tells you, I did my checks using `npm`.
Is it because we have different permissions on the repo or did you paste a wrong url ?

**Comment by dkarchmer** [comment]
<img width="859" alt="Screen Shot 2019-09-03 at 9 58 42 AM" src="https://user-images.githubusercontent.com/3330496/64193453-9f217480-ce31-11e9-9584-59cc401b6465.png">

**Comment by dkarchmer** [comment]
@mathispesch See if you can update these dependencies to solve the security warnings

<img width="555" alt="Screen Shot 2019-09-03 at 10 01 17 AM" src="https://user-images.githubusercontent.com/3330496/64193542-cf691300-ce31-11e9-8292-40cf94b13db6.png">

**Comment by mathispesch** [comment]
- For parsejson: not used anymore so I removed it
- For dot:
```
└─┬ @compodoc/compodoc@1.1.9
  └─┬ @compodoc/ngd-transformer@2.0.0
    └── dot@1.1.2 
```
[@compodoc/ngd-transformer](https://github.com/compodoc/ngd) hasn't been updated and the related issue on their GitHub seems inactive.

**Comment by mathispesch** [comment]
- `braces` requires upgrading Angular 6 to Angular 7. Will look into it. [(Angular 6 LTS ends in Nov. 2019](https://angular.io/guide/releases#support-policy-and-schedule)).

**Comment by mathispesch** [comment]
@dkarchmer I updated the dependencies to patched versions and corrected the few bugs (essentially dependencies ones).
`npm test` and `npm run build` both pass. How should I test that nothing broke?
